base = "../hal_config.toml"

[device]
name = "RP2040-One-Keypad-Default"
profile = "default"
description = "Standard 9-key layout with encoder"
modified = "2026-05-30T15:45:45.709663"

[encoder]
enabled = true
clk_gpio = 11
dt_gpio = 12
sw_gpio = 13
pull = "up"
debounce = 3
scroll_speed = 2
middle_click = false
steps_per_revolution = 24

[switches.switch_1]
gpio = 1
keycode = "Keycode.NINE"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+9"
pull = "up"
debounce = 10

[switches.switch_2]
gpio = 2
keycode = "Keycode.EIGHT"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+8"
pull = "up"
debounce = 10

[switches.switch_3]
gpio = 3
keycode = "Keycode.FIVE"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+5"
pull = "up"
debounce = 10

[switches.switch_4]
gpio = 29
keycode = "Keycode.ONE"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+1"
pull = "up"
debounce = 10

[switches.switch_5]
gpio = 4
keycode = "Keycode.SEVEN"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+7"
pull = "up"
debounce = 10

[switches.switch_6]
gpio = 5
keycode = "Keycode.SIX"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+6"
pull = "up"
debounce = 10

[switches.switch_7]
gpio = 6
keycode = "Keycode.FOUR"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+4"
pull = "up"
debounce = 10

[switches.switch_8]
gpio = 7
keycode = "Keycode.TWO"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+2"
pull = "up"
debounce = 10

[switches.switch_9]
gpio = 8
keycode = "Keycode.THREE"
modifier = "Keycode.CONTROL+Keycode.ALT"
label = "Ctrl+Alt+3"
pull = "up"
debounce = 10
