"""
RP2040-One HID Keypad — Web Configurator
==========================================
FastAPI backend: visual pin editor, code generator, wiring guide, flash instructions.

Uruchom:  make web        (lub:  uvicorn web.app:app --port 8080)
Dev:      make dev        (auto-reload)
Docker:   make docker-run
"""

from __future__ import annotations

import json
import os
import textwrap
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

# ============================================================================
# STAŁE
# ============================================================================

AVAILABLE_GPIOS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
                   16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

KEYCODES = {
    "ONE": "Keycode.ONE", "TWO": "Keycode.TWO", "THREE": "Keycode.THREE",
    "FOUR": "Keycode.FOUR", "FIVE": "Keycode.FIVE", "SIX": "Keycode.SIX",
    "SEVEN": "Keycode.SEVEN", "EIGHT": "Keycode.EIGHT", "NINE": "Keycode.NINE",
    "ZERO": "Keycode.ZERO",
    "A": "Keycode.A", "B": "Keycode.B", "C": "Keycode.C", "D": "Keycode.D",
    "E": "Keycode.E", "F": "Keycode.F", "G": "Keycode.G", "H": "Keycode.H",
    "I": "Keycode.I", "J": "Keycode.J", "K": "Keycode.K", "L": "Keycode.L",
    "M": "Keycode.M", "N": "Keycode.N", "O": "Keycode.O", "P": "Keycode.P",
    "Q": "Keycode.Q", "R": "Keycode.R", "S": "Keycode.S", "T": "Keycode.T",
    "U": "Keycode.U", "V": "Keycode.V", "W": "Keycode.W", "X": "Keycode.X",
    "Y": "Keycode.Y", "Z": "Keycode.Z",
    "F1": "Keycode.F1", "F2": "Keycode.F2", "F3": "Keycode.F3", "F4": "Keycode.F4",
    "F5": "Keycode.F5", "F6": "Keycode.F6", "F7": "Keycode.F7", "F8": "Keycode.F8",
    "F9": "Keycode.F9", "F10": "Keycode.F10", "F11": "Keycode.F11", "F12": "Keycode.F12",
    "SPACE": "Keycode.SPACE", "ENTER": "Keycode.ENTER", "ESCAPE": "Keycode.ESCAPE",
    "TAB": "Keycode.TAB", "BACKSPACE": "Keycode.BACKSPACE", "DELETE": "Keycode.DELETE",
    "UP": "Keycode.UP_ARROW", "DOWN": "Keycode.DOWN_ARROW",
    "LEFT": "Keycode.LEFT_ARROW", "RIGHT": "Keycode.RIGHT_ARROW",
    "HOME": "Keycode.HOME", "END": "Keycode.END",
    "PAGE_UP": "Keycode.PAGE_UP", "PAGE_DOWN": "Keycode.PAGE_DOWN",
}

MODIFIERS = {
    "CTRL": "Keycode.CONTROL",
    "ALT": "Keycode.ALT",
    "SHIFT": "Keycode.SHIFT",
    "GUI": "Keycode.GUI",
    "NONE": None,
}

# ============================================================================
# CONFIG MODEL
# ============================================================================

@dataclass
class KeyConfig:
    gpio: int
    keycode: str    # klucz z KEYCODES
    modifier: str   # klucz z MODIFIERS
    label: str = ""

@dataclass
class EncoderConfig:
    clk_gpio: int = 9
    dt_gpio: int = 10
    sw_gpio: int = 11
    scroll_speed: int = 2
    debounce_ms: int = 50

@dataclass
class PadConfig:
    keys: list[KeyConfig] = field(default_factory=lambda: [
        KeyConfig(1, "ONE", "CTRL", "Tab 1"),
        KeyConfig(2, "TWO", "CTRL", "Tab 2"),
        KeyConfig(3, "THREE", "CTRL", "Tab 3"),
        KeyConfig(4, "FOUR", "CTRL", "Tab 4"),
        KeyConfig(5, "FIVE", "CTRL", "Tab 5"),
        KeyConfig(6, "SIX", "CTRL", "Tab 6"),
        KeyConfig(7, "SEVEN", "CTRL", "Tab 7"),
        KeyConfig(8, "EIGHT", "CTRL", "Tab 8"),
        KeyConfig(29, "NINE", "CTRL", "Tab 9"),
    ])
    encoder: EncoderConfig = field(default_factory=EncoderConfig)

# ============================================================================
# CODE GENERATOR
# ============================================================================

def generate_code_py(cfg: PadConfig) -> str:
    key_lines = []
    for k in cfg.keys:
        kc = KEYCODES.get(k.keycode, "Keycode.ONE")
        comment = f"# {k.label}" if k.label else ""
        key_lines.append(f"    (board.GP{k.gpio}, {kc}),  {comment}")

    keys_block = "\n".join(key_lines)

    # Modifier logic
    mod_set = {k.modifier for k in cfg.keys}
    if len(mod_set) == 1:
        mod = list(mod_set)[0]
        mod_val = MODIFIERS.get(mod)
        if mod_val:
            press_line = f"keyboard.press({mod_val}, key['keycode'])"
            release_line = f"keyboard.release({mod_val}, key['keycode'])"
        else:
            press_line = "keyboard.press(key['keycode'])"
            release_line = "keyboard.release(key['keycode'])"
    else:
        # Per-key modifier stored in array — more complex variant
        press_line = "keyboard.press(key['modifier'], key['keycode'])" if any(
            MODIFIERS.get(k.modifier) for k in cfg.keys
        ) else "keyboard.press(key['keycode'])"
        release_line = press_line.replace("press", "release")

    enc = cfg.encoder

    return textwrap.dedent(f'''\
"""
RP2040-One HID Keypad + Encoder Mouse
Generated by Web Configurator — Softreck / Prototypowanie.pl
"""

import time
import board
import digitalio
import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keycode import Keycode
from adafruit_hid.mouse import Mouse

# ── Konfiguracja klawiszy ──
KEY_PINS = [
{keys_block}
]

# ── Konfiguracja enkodera ──
ENCODER_CLK_PIN = board.GP{enc.clk_gpio}
ENCODER_DT_PIN  = board.GP{enc.dt_gpio}
ENCODER_SW_PIN  = board.GP{enc.sw_gpio}
SCROLL_SPEED    = {enc.scroll_speed}
DEBOUNCE_MS     = {enc.debounce_ms}
ENCODER_DEBOUNCE_MS = 5

# ── HID init ──
keyboard = Keyboard(usb_hid.devices)
mouse = Mouse(usb_hid.devices)

# ── Piny klawiszy ──
keys = []
for pin, keycode in KEY_PINS:
    dio = digitalio.DigitalInOut(pin)
    dio.direction = digitalio.Direction.INPUT
    dio.pull = digitalio.Pull.UP
    keys.append(dict(pin=dio, keycode=keycode, last_state=True, last_change=0))

# ── Piny enkodera ──
encoder_clk = digitalio.DigitalInOut(ENCODER_CLK_PIN)
encoder_clk.direction = digitalio.Direction.INPUT
encoder_clk.pull = digitalio.Pull.UP

encoder_dt = digitalio.DigitalInOut(ENCODER_DT_PIN)
encoder_dt.direction = digitalio.Direction.INPUT
encoder_dt.pull = digitalio.Pull.UP

encoder_sw = digitalio.DigitalInOut(ENCODER_SW_PIN)
encoder_sw.direction = digitalio.Direction.INPUT
encoder_sw.pull = digitalio.Pull.UP

encoder_last_clk = encoder_clk.value
encoder_sw_last = True
encoder_sw_last_change = 0

# ── Główna pętla ──
while True:
    now = time.monotonic() * 1000

    for key in keys:
        current = key['pin'].value
        if current != key['last_state']:
            if (now - key['last_change']) > DEBOUNCE_MS:
                key['last_change'] = now
                key['last_state'] = current
                if not current:
                    {press_line}
                else:
                    {release_line}

    clk_val = encoder_clk.value
    if clk_val != encoder_last_clk:
        dt_val = encoder_dt.value
        if dt_val != clk_val:
            mouse.move(wheel=SCROLL_SPEED)
        else:
            mouse.move(wheel=-SCROLL_SPEED)
        encoder_last_clk = clk_val

    sw_val = encoder_sw.value
    if sw_val != encoder_sw_last:
        if (now - encoder_sw_last_change) > DEBOUNCE_MS:
            encoder_sw_last_change = now
            encoder_sw_last = sw_val
            if not sw_val:
                mouse.press(Mouse.MIDDLE_BUTTON)
            else:
                mouse.release(Mouse.MIDDLE_BUTTON)

    time.sleep(0.001)
''')


BOOT_PY = textwrap.dedent('''\
"""boot.py — USB HID: keyboard + mouse"""
import usb_hid
usb_hid.enable((usb_hid.Device.KEYBOARD, usb_hid.Device.MOUSE))
''')

# ============================================================================
# VALIDATION
# ============================================================================

def validate_config(cfg: PadConfig) -> list[str]:
    errors = []
    used = {}

    for i, k in enumerate(cfg.keys):
        g = k.gpio
        if g not in AVAILABLE_GPIOS:
            errors.append(f"Przycisk {i+1}: GP{g} nie istnieje na RP2040")
        if g in used:
            errors.append(f"Przycisk {i+1}: GP{g} już użyty przez {used[g]}")
        used[g] = f"Przycisk {i+1}"
        if k.keycode not in KEYCODES:
            errors.append(f"Przycisk {i+1}: nieznany keycode '{k.keycode}'")
        if k.modifier not in MODIFIERS:
            errors.append(f"Przycisk {i+1}: nieznany modifier '{k.modifier}'")

    enc = cfg.encoder
    for name, g in [("CLK", enc.clk_gpio), ("DT", enc.dt_gpio), ("SW", enc.sw_gpio)]:
        if g not in AVAILABLE_GPIOS:
            errors.append(f"Enkoder {name}: GP{g} nie istnieje")
        if g in used:
            errors.append(f"Enkoder {name}: GP{g} już użyty przez {used[g]}")
        used[g] = f"Enkoder {name}"

    if not (1 <= enc.scroll_speed <= 20):
        errors.append("scroll_speed musi być 1–20")
    if not (5 <= enc.debounce_ms <= 500):
        errors.append("debounce_ms musi być 5–500")

    return errors

# ============================================================================
# FASTAPI APP
# ============================================================================

app = FastAPI(title="RP2040-One Keypad Configurator", version="1.0.0")

OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True)


@app.get("/", response_class=HTMLResponse)
async def index():
    return FRONTEND_HTML


@app.get("/api/defaults")
async def api_defaults():
    cfg = PadConfig()
    return {
        "keys": [asdict(k) for k in cfg.keys],
        "encoder": asdict(cfg.encoder),
        "available_keycodes": list(KEYCODES.keys()),
        "available_modifiers": list(MODIFIERS.keys()),
        "available_gpios": AVAILABLE_GPIOS,
    }


@app.post("/api/validate")
async def api_validate(request: Request):
    data = await request.json()
    cfg = _parse_config(data)
    errors = validate_config(cfg)
    return {"valid": len(errors) == 0, "errors": errors}


@app.post("/api/generate")
async def api_generate(request: Request):
    data = await request.json()
    cfg = _parse_config(data)
    errors = validate_config(cfg)
    if errors:
        return JSONResponse({"errors": errors}, status_code=400)

    code = generate_code_py(cfg)
    boot = BOOT_PY

    OUTPUT_DIR.mkdir(exist_ok=True)
    (OUTPUT_DIR / "code.py").write_text(code)
    (OUTPUT_DIR / "boot.py").write_text(boot)

    return {
        "code_py": code,
        "boot_py": boot,
        "message": "Pliki wygenerowane i zapisane w output/"
    }


@app.get("/api/download/code.py", response_class=PlainTextResponse)
async def download_code():
    p = OUTPUT_DIR / "code.py"
    if not p.exists():
        return PlainTextResponse("Najpierw wygeneruj config", status_code=404)
    return PlainTextResponse(p.read_text(), media_type="text/x-python",
                             headers={"Content-Disposition": "attachment; filename=code.py"})


@app.get("/api/download/boot.py", response_class=PlainTextResponse)
async def download_boot():
    return PlainTextResponse(BOOT_PY, media_type="text/x-python",
                             headers={"Content-Disposition": "attachment; filename=boot.py"})


def _parse_config(data: dict) -> PadConfig:
    keys = []
    for k in data.get("keys", []):
        keys.append(KeyConfig(
            gpio=int(k["gpio"]),
            keycode=str(k["keycode"]),
            modifier=str(k.get("modifier", "CTRL")),
            label=str(k.get("label", "")),
        ))
    enc_data = data.get("encoder", {})
    enc = EncoderConfig(
        clk_gpio=int(enc_data.get("clk_gpio", 9)),
        dt_gpio=int(enc_data.get("dt_gpio", 10)),
        sw_gpio=int(enc_data.get("sw_gpio", 11)),
        scroll_speed=int(enc_data.get("scroll_speed", 2)),
        debounce_ms=int(enc_data.get("debounce_ms", 50)),
    )
    return PadConfig(keys=keys, encoder=enc)


# ============================================================================
# FRONTEND — Single-page HTML app
# ============================================================================

FRONTEND_HTML = r"""<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RP2040-One Keypad Configurator</title>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;800&family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#0c0e13;--bg2:#14171f;--bg3:#1c2029;--bg4:#252a35;
  --fg:#e4e8f1;--fg2:#9aa0b4;--fg3:#636a7e;
  --acc:#38d9a9;--acc2:#20c997;--acc-dim:rgba(56,217,169,.12);
  --err:#ff6b6b;--err-dim:rgba(255,107,107,.12);
  --warn:#ffd43b;--blue:#4dabf7;
  --radius:10px;--mono:'JetBrains Mono',monospace;--sans:'DM Sans',sans-serif;
}
html{font-size:15px}
body{background:var(--bg);color:var(--fg);font-family:var(--sans);min-height:100vh;overflow-x:hidden}

/* ── HEADER ─── */
header{
  background:linear-gradient(135deg,#0d1117 0%,#161b22 100%);
  border-bottom:1px solid var(--bg4);
  padding:1.4rem 2rem;display:flex;align-items:center;gap:1.2rem;
  position:sticky;top:0;z-index:100;backdrop-filter:blur(12px)
}
header .chip{
  background:var(--acc-dim);color:var(--acc);font-family:var(--mono);
  font-size:.7rem;font-weight:800;padding:.25rem .6rem;border-radius:4px;
  letter-spacing:.08em;text-transform:uppercase
}
header h1{font-size:1.15rem;font-weight:700;letter-spacing:-.02em}
header h1 span{color:var(--acc)}
.header-actions{margin-left:auto;display:flex;gap:.6rem}

/* ── LAYOUT ─── */
.container{max-width:1280px;margin:0 auto;padding:1.5rem 2rem 4rem}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem}
@media(max-width:960px){.grid{grid-template-columns:1fr}}

/* ── PANELS ─── */
.panel{
  background:var(--bg2);border:1px solid var(--bg4);border-radius:var(--radius);
  overflow:hidden
}
.panel-head{
  padding:.9rem 1.2rem;border-bottom:1px solid var(--bg4);
  display:flex;align-items:center;gap:.6rem;
  font-weight:700;font-size:.85rem;letter-spacing:.02em
}
.panel-head .dot{width:8px;height:8px;border-radius:50%;flex-shrink:0}
.panel-body{padding:1.2rem}

/* ── TABLE/KEY ROW ─── */
.key-row{
  display:grid;grid-template-columns:36px 80px 1fr 120px 150px 42px;
  gap:.5rem;align-items:center;padding:.45rem 0;
  border-bottom:1px solid var(--bg3)
}
.key-row:last-child{border-bottom:none}
.key-row .idx{
  font-family:var(--mono);font-size:.75rem;color:var(--fg3);text-align:center
}
.key-row input,.key-row select{
  background:var(--bg3);border:1px solid transparent;color:var(--fg);
  padding:.4rem .55rem;border-radius:6px;font-size:.82rem;
  font-family:var(--mono);outline:none;transition:.15s
}
.key-row input:focus,.key-row select:focus{border-color:var(--acc);box-shadow:0 0 0 2px var(--acc-dim)}
.key-row select{cursor:pointer;appearance:none;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6'%3E%3Cpath d='M0 0l5 6 5-6z' fill='%239aa0b4'/%3E%3C/svg%3E");
  background-repeat:no-repeat;background-position:right .5rem center;padding-right:1.6rem}
.key-row .label-input{font-family:var(--sans)}

.del-btn{
  background:none;border:none;color:var(--fg3);cursor:pointer;
  font-size:1.1rem;border-radius:6px;width:32px;height:32px;
  display:flex;align-items:center;justify-content:center;transition:.15s
}
.del-btn:hover{background:var(--err-dim);color:var(--err)}

/* ── ENCODER PANEL ─── */
.enc-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:.8rem}
.enc-field label{display:block;font-size:.72rem;color:var(--fg3);
  font-family:var(--mono);margin-bottom:.3rem;text-transform:uppercase;letter-spacing:.06em}
.enc-field input,.enc-field select{
  width:100%;background:var(--bg3);border:1px solid transparent;color:var(--fg);
  padding:.5rem .6rem;border-radius:6px;font-family:var(--mono);font-size:.85rem;outline:none;transition:.15s
}
.enc-field input:focus,.enc-field select:focus{border-color:var(--acc);box-shadow:0 0 0 2px var(--acc-dim)}

/* ── PINOUT SVG ─── */
.pinout-wrap{display:flex;justify-content:center;padding:1rem}
.pinout-wrap svg{max-width:100%}
.pin-used{fill:var(--acc);opacity:.85}
.pin-enc{fill:var(--blue);opacity:.85}
.pin-free{fill:var(--bg4)}

/* ── CODE PREVIEW ─── */
.code-box{
  background:#0d1117;border:1px solid var(--bg4);border-radius:8px;
  padding:1rem;max-height:460px;overflow:auto;
  font-family:var(--mono);font-size:.78rem;line-height:1.55;
  color:#c9d1d9;white-space:pre;tab-size:4
}
.code-box .kw{color:#ff7b72}
.code-box .str{color:#a5d6ff}
.code-box .cmt{color:#8b949e;font-style:italic}

/* ── BUTTONS ─── */
.btn{
  display:inline-flex;align-items:center;gap:.4rem;
  padding:.55rem 1.1rem;border:none;border-radius:7px;
  font-family:var(--sans);font-weight:600;font-size:.82rem;
  cursor:pointer;transition:.2s;text-decoration:none
}
.btn-primary{background:var(--acc);color:#0c0e13}
.btn-primary:hover{background:var(--acc2);transform:translateY(-1px);box-shadow:0 4px 14px rgba(56,217,169,.3)}
.btn-ghost{background:var(--bg3);color:var(--fg)}
.btn-ghost:hover{background:var(--bg4)}
.btn-danger{background:var(--err-dim);color:var(--err)}
.btn-danger:hover{background:rgba(255,107,107,.2)}
.btn-sm{padding:.35rem .7rem;font-size:.75rem}
.btn svg{width:16px;height:16px}
.btn-group{display:flex;gap:.5rem;flex-wrap:wrap}

/* ── TOAST ─── */
.toast{
  position:fixed;bottom:1.5rem;right:1.5rem;
  background:var(--bg3);border:1px solid var(--bg4);
  padding:.8rem 1.2rem;border-radius:8px;font-size:.82rem;
  display:none;z-index:200;max-width:380px;
  box-shadow:0 8px 24px rgba(0,0,0,.4);animation:slideUp .3s ease
}
.toast.ok{border-left:3px solid var(--acc)}
.toast.err{border-left:3px solid var(--err)}
@keyframes slideUp{from{transform:translateY(20px);opacity:0}to{transform:translateY(0);opacity:1}}

/* ── TABS ─── */
.tabs{display:flex;gap:2px;margin-bottom:1rem;background:var(--bg3);padding:3px;border-radius:8px;width:fit-content}
.tab{
  padding:.4rem .9rem;border-radius:6px;font-size:.78rem;font-weight:600;
  cursor:pointer;color:var(--fg3);transition:.15s;border:none;background:none
}
.tab.active{background:var(--bg);color:var(--fg);box-shadow:0 1px 4px rgba(0,0,0,.2)}

/* ── INSTRUCTIONS ─── */
.steps{counter-reset:step}
.step{
  counter-increment:step;position:relative;
  padding:.8rem 0 .8rem 2.8rem;border-left:2px solid var(--bg4);margin-left:.7rem
}
.step::before{
  content:counter(step);position:absolute;left:-12px;top:.7rem;
  width:22px;height:22px;border-radius:50%;
  background:var(--acc);color:var(--bg);
  font-family:var(--mono);font-size:.7rem;font-weight:800;
  display:flex;align-items:center;justify-content:center
}
.step:last-child{border-left-color:transparent}
.step h4{font-size:.85rem;margin-bottom:.3rem}
.step p{font-size:.8rem;color:var(--fg2);line-height:1.5}
.step code{
  background:var(--bg3);padding:.15rem .4rem;border-radius:4px;
  font-family:var(--mono);font-size:.75rem
}

/* ── WIRING TABLE ─── */
.wire-tbl{width:100%;border-collapse:collapse;font-size:.8rem}
.wire-tbl th{
  text-align:left;padding:.5rem .6rem;font-weight:600;font-size:.72rem;
  color:var(--fg3);text-transform:uppercase;letter-spacing:.06em;
  border-bottom:2px solid var(--bg4)
}
.wire-tbl td{padding:.45rem .6rem;border-bottom:1px solid var(--bg3)}
.wire-tbl .pin-tag{
  display:inline-block;padding:.1rem .4rem;border-radius:4px;
  font-family:var(--mono);font-size:.72rem;font-weight:600
}
.wire-tbl .pin-key{background:var(--acc-dim);color:var(--acc)}
.wire-tbl .pin-enc{background:rgba(77,171,247,.12);color:var(--blue)}

/* ── ERRORS ─── */
.error-list{list-style:none;padding:0}
.error-list li{
  padding:.35rem .6rem;margin-bottom:.3rem;border-radius:5px;
  background:var(--err-dim);color:var(--err);font-size:.78rem;
  font-family:var(--mono)
}
</style>
</head>
<body>

<header>
  <div class="chip">HID</div>
  <h1><span>RP2040-One</span> Keypad Configurator</h1>
  <div class="header-actions">
    <button class="btn btn-ghost btn-sm" onclick="resetDefaults()">Reset</button>
    <button class="btn btn-primary btn-sm" onclick="generateCode()">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><polyline points="13 2 13 9 20 9"/></svg>
      Generuj
    </button>
  </div>
</header>

<div class="container">

  <div class="tabs" id="mainTabs">
    <button class="tab active" data-tab="config">Konfiguracja</button>
    <button class="tab" data-tab="wiring">Schemat</button>
    <button class="tab" data-tab="code">Kod</button>
    <button class="tab" data-tab="flash">Instrukcje</button>
  </div>

  <!-- ═══════ TAB: CONFIG ═══════ -->
  <div class="tab-content" id="tab-config">
    <div class="grid">

      <!-- Keys panel -->
      <div class="panel">
        <div class="panel-head">
          <div class="dot" style="background:var(--acc)"></div>
          Klawisze (emulacja klawiatury)
        </div>
        <div class="panel-body">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:.7rem">
            <span style="font-size:.72rem;color:var(--fg3);font-family:var(--mono)">GPIO → MODIFIER + KEY</span>
            <button class="btn btn-ghost btn-sm" onclick="addKey()">+ Dodaj</button>
          </div>
          <div id="keysContainer"></div>
          <div id="keyErrors" style="margin-top:.6rem"></div>
        </div>
      </div>

      <!-- Encoder panel -->
      <div>
        <div class="panel" style="margin-bottom:1.5rem">
          <div class="panel-head">
            <div class="dot" style="background:var(--blue)"></div>
            Enkoder obrotowy (emulacja myszki)
          </div>
          <div class="panel-body">
            <div class="enc-grid">
              <div class="enc-field"><label>CLK (A)</label><input type="number" id="encClk" min="0" max="29" value="9"></div>
              <div class="enc-field"><label>DT (B)</label><input type="number" id="encDt" min="0" max="29" value="10"></div>
              <div class="enc-field"><label>SW (przycisk)</label><input type="number" id="encSw" min="0" max="29" value="11"></div>
              <div class="enc-field"><label>Scroll speed</label><input type="number" id="encSpeed" min="1" max="20" value="2"></div>
              <div class="enc-field"><label>Debounce (ms)</label><input type="number" id="encDebounce" min="5" max="500" value="50"></div>
            </div>
            <div style="margin-top:.8rem;font-size:.75rem;color:var(--fg3)">
              Obrót CW → scroll w górę&ensp;|&ensp;Obrót CCW → scroll w dół&ensp;|&ensp;Przycisk → middle-click
            </div>
          </div>
        </div>

        <!-- Live pinout -->
        <div class="panel">
          <div class="panel-head">
            <div class="dot" style="background:var(--warn)"></div>
            Pinout RP2040-One (live)
          </div>
          <div class="panel-body">
            <div class="pinout-wrap" id="pinoutSvg"></div>
            <div style="display:flex;gap:1rem;justify-content:center;font-size:.72rem;color:var(--fg3);margin-top:.5rem">
              <span><span style="color:var(--acc)">●</span> Klawisze</span>
              <span><span style="color:var(--blue)">●</span> Enkoder</span>
              <span><span style="color:var(--bg4)">●</span> Wolne</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- ═══════ TAB: WIRING ═══════ -->
  <div class="tab-content" id="tab-wiring" style="display:none">
    <div class="panel">
      <div class="panel-head">
        <div class="dot" style="background:var(--warn)"></div>
        Schemat podłączeń
      </div>
      <div class="panel-body">
        <table class="wire-tbl" id="wiringTable"></table>
      </div>
    </div>
  </div>

  <!-- ═══════ TAB: CODE ═══════ -->
  <div class="tab-content" id="tab-code" style="display:none">
    <div class="panel">
      <div class="panel-head">
        <div class="dot" style="background:var(--acc)"></div>
        code.py
        <div style="margin-left:auto" class="btn-group">
          <button class="btn btn-ghost btn-sm" onclick="copyCode()">Kopiuj</button>
          <a class="btn btn-primary btn-sm" href="/api/download/code.py" download>Pobierz</a>
        </div>
      </div>
      <div class="panel-body">
        <div class="code-box" id="codePreview">Kliknij "Generuj" aby wygenerować kod...</div>
      </div>
    </div>
    <div class="panel" style="margin-top:1rem">
      <div class="panel-head">
        <div class="dot" style="background:var(--blue)"></div>
        boot.py
        <a class="btn btn-ghost btn-sm" href="/api/download/boot.py" download style="margin-left:auto">Pobierz</a>
      </div>
      <div class="panel-body">
        <div class="code-box" id="bootPreview"># boot.py -- USB HID: keyboard + mouse
import usb_hid
usb_hid.enable((usb_hid.Device.KEYBOARD, usb_hid.Device.MOUSE))</div>
      </div>
    </div>
  </div>

  <!-- ═══════ TAB: FLASH ═══════ -->
  <div class="tab-content" id="tab-flash" style="display:none">
    <div class="panel">
      <div class="panel-head">
        <div class="dot" style="background:var(--acc)"></div>
        Instrukcja nagrywania na RP2040-One
      </div>
      <div class="panel-body">
        <div class="steps">
          <div class="step">
            <h4>Pobierz CircuitPython UF2</h4>
            <p>Otwórz <a href="https://circuitpython.org/board/waveshare_rp2040_one/" target="_blank" style="color:var(--acc)">circuitpython.org</a> i pobierz plik <code>.uf2</code> (wersja 9.x).</p>
          </div>
          <div class="step">
            <h4>Wgraj firmware</h4>
            <p>Odłącz RP2040-One. Przytrzymaj <code>BOOT</code> → włóż do USB-A → zwolnij. Pojawi się dysk <code>RPI-RP2</code>. Skopiuj na niego plik <code>.uf2</code>.</p>
          </div>
          <div class="step">
            <h4>Poczekaj na restart</h4>
            <p>Płytka zrestartuje się automatycznie. Pojawi się dysk <code>CIRCUITPY</code>.</p>
          </div>
          <div class="step">
            <h4>Zainstaluj bibliotekę adafruit_hid</h4>
            <p>Pobierz <a href="https://circuitpython.org/libraries" target="_blank" style="color:var(--acc)">Adafruit Bundle</a> → rozpakuj → skopiuj folder <code>lib/adafruit_hid/</code> do <code>CIRCUITPY/lib/</code>.</p>
          </div>
          <div class="step">
            <h4>Skopiuj wygenerowane pliki</h4>
            <p>Skopiuj <code>boot.py</code> i <code>code.py</code> do katalogu głównego <code>CIRCUITPY/</code>. Lub użyj: <code>make flash</code></p>
          </div>
          <div class="step">
            <h4>Odłącz i podłącz ponownie</h4>
            <p><code>boot.py</code> działa TYLKO przy starcie USB. Po ponownym podłączeniu system rozpozna klawiaturę + myszkę.</p>
          </div>
          <div class="step">
            <h4>Testuj!</h4>
            <p>Wciśnij przycisk → powinien zadziałać skrót. Obróć enkoder → scroll. Wciśnij enkoder → middle-click.</p>
          </div>
        </div>

        <div style="margin-top:1.5rem;padding:1rem;background:var(--bg3);border-radius:8px">
          <h4 style="font-size:.82rem;margin-bottom:.5rem">Komendy Makefile</h4>
          <div class="code-box" style="font-size:.75rem;max-height:200px">make install      # Zainstaluj zależności Python
make web          # Uruchom web configurator
make flash        # Wgraj na podłączone CIRCUITPY
make test         # Testy jednostkowe
make test-docker  # Testy E2E w Docker
make test-e2e     # Docker Compose testy E2E
make download-uf2 # Pobierz firmware CircuitPython</div>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="toast" id="toast"></div>

<script>
// ── STATE ──
let keycodes = [], modifiers = [], gpios = [];
let keys = [];

// ── INIT ──
async function init() {
  const r = await fetch('/api/defaults');
  const d = await r.json();
  keycodes = d.available_keycodes;
  modifiers = d.available_modifiers;
  gpios = d.available_gpios;
  keys = d.keys;
  renderKeys();
  renderPinout();
  renderWiring();
}

// ── TABS ──
document.querySelectorAll('.tab').forEach(t => {
  t.addEventListener('click', () => {
    document.querySelectorAll('.tab').forEach(x => x.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(x => x.style.display = 'none');
    t.classList.add('active');
    document.getElementById('tab-' + t.dataset.tab).style.display = '';
    if (t.dataset.tab === 'wiring') renderWiring();
  });
});

// ── RENDER KEYS ──
function renderKeys() {
  const c = document.getElementById('keysContainer');
  c.innerHTML = '';
  keys.forEach((k, i) => {
    const row = document.createElement('div');
    row.className = 'key-row';
    row.innerHTML = `
      <div class="idx">${i + 1}</div>
      <input type="number" min="0" max="29" value="${k.gpio}" 
             onchange="keys[${i}].gpio=+this.value;renderPinout()" 
             style="width:70px" title="GPIO pin">
      <input class="label-input" value="${k.label}" 
             onchange="keys[${i}].label=this.value" 
             placeholder="Opis...">
      <select onchange="keys[${i}].modifier=this.value">
        ${modifiers.map(m => `<option value="${m}" ${m===k.modifier?'selected':''}>${m}</option>`).join('')}
      </select>
      <select onchange="keys[${i}].keycode=this.value">
        ${keycodes.map(kc => `<option value="${kc}" ${kc===k.keycode?'selected':''}>${kc}</option>`).join('')}
      </select>
      <button class="del-btn" onclick="keys.splice(${i},1);renderKeys();renderPinout()" title="Usuń">×</button>
    `;
    c.appendChild(row);
  });
}

function addKey() {
  const used = new Set(keys.map(k => k.gpio));
  const enc = [+document.getElementById('encClk').value, +document.getElementById('encDt').value, +document.getElementById('encSw').value];
  enc.forEach(g => used.add(g));
  const free = gpios.find(g => !used.has(g) && g !== 0) || 0;
  keys.push({ gpio: free, keycode: 'A', modifier: 'CTRL', label: '' });
  renderKeys();
  renderPinout();
}

function resetDefaults() {
  fetch('/api/defaults').then(r => r.json()).then(d => {
    keys = d.keys;
    document.getElementById('encClk').value = d.encoder.clk_gpio;
    document.getElementById('encDt').value = d.encoder.dt_gpio;
    document.getElementById('encSw').value = d.encoder.sw_gpio;
    document.getElementById('encSpeed').value = d.encoder.scroll_speed;
    document.getElementById('encDebounce').value = d.encoder.debounce_ms;
    renderKeys(); renderPinout(); renderWiring();
    toast('Reset do domyślnych', 'ok');
  });
}

// ── PINOUT SVG ──
function renderPinout() {
  const usedKeys = new Set(keys.map(k => k.gpio));
  const encPins = new Set([+document.getElementById('encClk').value, +document.getElementById('encDt').value, +document.getElementById('encSw').value]);
  const left = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15];
  const right = [29,28,27,26,25,24,23,22,21,20,19,18,17,16];

  let svg = `<svg width="320" height="380" viewBox="0 0 320 380" xmlns="http://www.w3.org/2000/svg">`;
  svg += `<rect x="90" y="10" width="140" height="360" rx="8" fill="#1c2029" stroke="#363c4a" stroke-width="1.5"/>`;
  svg += `<rect x="120" y="2" width="80" height="22" rx="4" fill="#252a35" stroke="#363c4a"/>`;
  svg += `<text x="160" y="16" text-anchor="middle" fill="#636a7e" font-size="9" font-family="JetBrains Mono">USB-A</text>`;

  function pinCircle(x, y, gpio) {
    const cls = usedKeys.has(gpio) ? 'pin-used' : encPins.has(gpio) ? 'pin-enc' : 'pin-free';
    svg += `<circle cx="${x}" cy="${y}" r="8" class="${cls}"/>`;
    svg += `<text x="${x}" y="${y+3.5}" text-anchor="middle" fill="${cls==='pin-free'?'#636a7e':'#0c0e13'}" font-size="7" font-weight="600" font-family="JetBrains Mono">${gpio}</text>`;
  }

  left.forEach((g, i) => {
    const y = 45 + i * 20;
    pinCircle(76, y, g);
    svg += `<text x="60" y="${y+3.5}" text-anchor="end" fill="#636a7e" font-size="8" font-family="JetBrains Mono">GP${g}</text>`;
  });
  right.forEach((g, i) => {
    const y = 45 + i * 20;
    pinCircle(244, y, g);
    svg += `<text x="260" y="${y+3.5}" text-anchor="start" fill="#636a7e" font-size="8" font-family="JetBrains Mono">GP${g}</text>`;
  });

  // Power pins
  svg += `<text x="160" y="356" text-anchor="middle" fill="#636a7e" font-size="8" font-family="JetBrains Mono">3V3 · GND</text>`;
  svg += `</svg>`;

  document.getElementById('pinoutSvg').innerHTML = svg;
}

// ── WIRING TABLE ──
function renderWiring() {
  const tbl = document.getElementById('wiringTable');
  let html = `<tr><th>Element</th><th>Pin RP2040</th><th>Podłączenie</th><th>Funkcja HID</th></tr>`;
  keys.forEach((k, i) => {
    const mod = k.modifier !== 'NONE' ? k.modifier + '+' : '';
    html += `<tr>
      <td>Przycisk ${i+1}</td>
      <td><span class="pin-tag pin-key">GP${k.gpio}</span></td>
      <td>Switch → GND</td>
      <td>${mod}${k.keycode}</td>
    </tr>`;
  });
  const encClk = document.getElementById('encClk').value;
  const encDt = document.getElementById('encDt').value;
  const encSw = document.getElementById('encSw').value;
  html += `<tr><td>Enkoder CLK</td><td><span class="pin-tag pin-enc">GP${encClk}</span></td><td>Encoder A</td><td>Scroll direction</td></tr>`;
  html += `<tr><td>Enkoder DT</td><td><span class="pin-tag pin-enc">GP${encDt}</span></td><td>Encoder B</td><td>Scroll direction</td></tr>`;
  html += `<tr><td>Enkoder SW</td><td><span class="pin-tag pin-enc">GP${encSw}</span></td><td>Switch → GND</td><td>Middle-click</td></tr>`;
  html += `<tr><td>Enkoder VCC</td><td><span class="pin-tag" style="background:var(--bg3);color:var(--fg3)">3V3</span></td><td>Zasilanie</td><td>—</td></tr>`;
  html += `<tr><td>Enkoder + BTN GND</td><td><span class="pin-tag" style="background:var(--bg3);color:var(--fg3)">GND</span></td><td>Wspólna masa</td><td>—</td></tr>`;
  tbl.innerHTML = html;
}

// ── GENERATE ──
async function generateCode() {
  const cfg = getConfig();
  const r = await fetch('/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(cfg)
  });
  const d = await r.json();
  if (!r.ok) {
    document.getElementById('keyErrors').innerHTML =
      `<ul class="error-list">${d.errors.map(e => `<li>${e}</li>`).join('')}</ul>`;
    toast('Błędy walidacji!', 'err');
    return;
  }
  document.getElementById('keyErrors').innerHTML = '';
  document.getElementById('codePreview').textContent = d.code_py;
  // Switch to code tab
  document.querySelectorAll('.tab').forEach(x => x.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(x => x.style.display = 'none');
  document.querySelector('[data-tab="code"]').classList.add('active');
  document.getElementById('tab-code').style.display = '';
  toast('Kod wygenerowany i zapisany w output/', 'ok');
}

function copyCode() {
  const text = document.getElementById('codePreview').textContent;
  navigator.clipboard.writeText(text).then(() => toast('Skopiowano do schowka', 'ok'));
}

function getConfig() {
  return {
    keys: keys,
    encoder: {
      clk_gpio: +document.getElementById('encClk').value,
      dt_gpio: +document.getElementById('encDt').value,
      sw_gpio: +document.getElementById('encSw').value,
      scroll_speed: +document.getElementById('encSpeed').value,
      debounce_ms: +document.getElementById('encDebounce').value,
    }
  };
}

// ── TOAST ──
function toast(msg, type) {
  const t = document.getElementById('toast');
  t.textContent = msg;
  t.className = 'toast ' + type;
  t.style.display = 'block';
  setTimeout(() => { t.style.display = 'none'; }, 3000);
}

// ── Encoder fields trigger pinout update ──
['encClk','encDt','encSw'].forEach(id => {
  document.getElementById(id).addEventListener('change', () => { renderPinout(); renderWiring(); });
});

init();
</script>
</body>
</html>"""
